/*******************************************************************************
 * Copyright (C) 2010-2019 Goran Schwarz
 * 
 * This file is part of DbxTune
 * DbxTune is a family of sub-products *Tune, hence the Dbx
 * Here are some of the tools: AseTune, IqTune, RsTune, RaxTune, HanaTune, 
 *          SqlServerTune, PostgresTune, MySqlTune, MariaDbTune, Db2Tune, ...
 * 
 * DbxTune is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * DbxTune is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DbxTune.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package com.dbxtune.utils;


import java.awt.Desktop;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.invoke.MethodHandles;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

import org.apache.commons.mail.EmailConstants;
import org.apache.commons.mail.EmailException;
import org.apache.commons.mail.HtmlEmail;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.dbxtune.gui.ResultSetTableModel;
import com.dbxtune.sql.conn.DbxConnection;
import com.dbxtune.utils.SpaceFullPredictor.PredictionResult;
import com.dbxtune.utils.TimeSeriesAnalyzer.AggregatedDataPoint;
import com.dbxtune.utils.TimeSeriesAnalyzer.ITsDataPoint;
import com.dbxtune.utils.TimeSeriesAnalyzer.SparklineType;
import com.dbxtune.utils.TimeSeriesAnalyzer.TsDataPoint;



///**
// * Predicts when a disk/file system will become full based on historical usage data.
// * Handles daily peaks by using percentile-based filtering.
// * 
// * Can be reused for:
// * - Filesystem space prediction (df command data)
// * - Database data/log space prediction (Sybase, SQL Server)
// * - Or any other when we have multiple samples of 'name', 'totalSize', 'usedSize', 'freeSize' stored in a DBMS Table
// */
/**
 * NOTE: Most of the Algorithms Used are generated by AI (I'm not a Math Wizard... So I took help from AI)
 * <p>
 * 
 * DiskFullPredictor estimates when a disk (or logical volume such as a DBMS
 * data or log file) will become full based on historical size and free-space samples.
 *
 * <p>Typical Input:</p>
 * <ul>
 *   <li>Time-series samples containing:
 *       <ul>
 *         <li>Resource Name -- Name of Disk or Database</li>
 *         <li>Timestamp</li>
 *         <li>Total size (KB)</li>
 *         <li>Used size (KB)</li>
 *         <li>Free size (KB)</li>
 *       </ul>
 *   </li>
 * </ul>
 *
 * <p>Computed metrics:</p>
 * <ul>
 *   <li>Used percentage = usedKB / totalKB * 100</li>
 *   <li>Growth rate (KB/hour) using linear regression</li>
 *   <li>Estimated hours until full = currentFreeKB / growthRate</li>
 * </ul>
 *
 * <p>Algorithm:</p>
 * <ol>
 *   <li>Samples are grouped by disk / file name.</li>
 *   <li>For each group, the code builds a time series of (time, usedKB) points.</li>
 *   <li>Simple least-squares linear regression is applied:
 *       <pre>
 *       y = a + b * x
 *       where:
 *         x = time (hours since first sample)
 *         y = used space in KB
 *         b = growth slope in KB/hour
 *       </pre>
 *   </li>
 *   <li>The slope {@code b} represents the average growth rate.</li>
 *   <li>Remaining time is extrapolated assuming linear growth:
 *       <pre>
 *       hoursUntilFull = currentFreeKB / b
 *       </pre>
 *   </li>
 * </ol>
 *
 * <p>Assumptions and limitations:</p>
 * <ul>
 *   <li>Growth is approximately linear over the observed period.</li>
 *   <li>No future autogrowth, file resizing, cleanup, or retention changes are modeled.</li>
 *   <li>Very small databases or nearly flat growth can produce unstable predictions
 *       due to floating-point noise or near-zero slopes.</li>
 *   <li>Predictions are invalid if the regression slope is zero or negative.</li>
 * </ul>
 *
 */
public class SpaceFullPredictor
{
	private static final Logger _logger = LogManager.getLogger(MethodHandles.lookup().lookupClass());

	// Date/time formatter for consistent timestamp display
	private static final DateTimeFormatter TIMESTAMP_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
	
	public static final String  PROPKEY_percentileFilter                  = "SpaceFullPredictor.percentileFilter";
	public static final String  PROPKEY_hoursOfHistory                    = "SpaceFullPredictor.hoursOfHistory";
	public static final String  PROPKEY_criticalThresholdHours            = "SpaceFullPredictor.criticalThresholdHours";
	public static final String  PROPKEY_warningThresholdHours             = "SpaceFullPredictor.warningThresholdHours";
	public static final String  PROPKEY_formatMbLessThanMbUsingOneDecimal = "SpaceFullPredictor.formatMbLessThanMbUsingOneDecimal";
	public static final String  PROPKEY_createSparkLines                  = "SpaceFullPredictor.createSparkLines";
	public static final String  PROPKEY_sparkLineGroupDataByMinutes       = "SpaceFullPredictor.sparkLine.groupDataByMinutes";

	public static final int     DEFAULT_percentileFilter                  = Configuration.getCombinedConfiguration().getIntProperty    (PROPKEY_percentileFilter                 , 75);
	public static final int     DEFAULT_hoursOfHistory                    = Configuration.getCombinedConfiguration().getIntProperty    (PROPKEY_hoursOfHistory                   , -1);
	public static final int     DEFAULT_criticalThresholdHours            = Configuration.getCombinedConfiguration().getIntProperty    (PROPKEY_criticalThresholdHours           , 7  * 24);
	public static final int     DEFAULT_warningThresholdHours             = Configuration.getCombinedConfiguration().getIntProperty    (PROPKEY_warningThresholdHours            , 14 * 24);
	public static final double  DEFAULT_formatMbLessThanMbUsingOneDecimal = Configuration.getCombinedConfiguration().getDoubleProperty (PROPKEY_formatMbLessThanMbUsingOneDecimal, 100.0);
	public static final boolean DEFAULT_createSparkLines                  = Configuration.getCombinedConfiguration().getBooleanProperty(PROPKEY_createSparkLines                 , true);
	public static final int     DEFAULT_sparkLineGroupDataByMinutes       = Configuration.getCombinedConfiguration().getIntProperty    (PROPKEY_sparkLineGroupDataByMinutes      , 10);
	
	private static final double EPSILON = 1.0; // KB per hour

	public static final String  CRITICAL = "CRITICAL";
	public static final String  WARNING  = "WARNING";
	public static final String  OK       = "OK";
	public static final String  NO_DATA  = "NO DATA";


	////////////////////////////////////////////////////////
	// Members
	////////////////////////////////////////////////////////
	private DbxConnection _conn;
	private int           _percentileFilter                  = DEFAULT_percentileFilter;
	private int           _hoursOfHistory                    = DEFAULT_hoursOfHistory;

	private int           _criticalThresholdHours            = DEFAULT_criticalThresholdHours;
	private int           _warningThresholdHours             = DEFAULT_warningThresholdHours;
	
	private double        _formatMbLessThanMbUsingOneDecimal = DEFAULT_formatMbLessThanMbUsingOneDecimal;

	private boolean       _createSparkLines                  = DEFAULT_createSparkLines;
	private int           _sparkLineGroupDataByMinutes       = DEFAULT_sparkLineGroupDataByMinutes;

	////////////////////////////////////////////////////////
	// BEGIN: Constructors
	////////////////////////////////////////////////////////
	public SpaceFullPredictor(DbxConnection conn)
	{
		this(conn, DEFAULT_percentileFilter, DEFAULT_hoursOfHistory, DEFAULT_criticalThresholdHours, DEFAULT_warningThresholdHours);
	}

	public SpaceFullPredictor(DbxConnection conn, int percentileFilter)
	{
		this(conn, percentileFilter, DEFAULT_hoursOfHistory, DEFAULT_criticalThresholdHours, DEFAULT_warningThresholdHours);
	}

	public SpaceFullPredictor(DbxConnection conn, int percentileFilter, int hoursOfHistory, int criticalThresholdHours, int warningThresholdHours)
	{
		if (percentileFilter < 1 || percentileFilter > 99) 
		{
			throw new IllegalArgumentException("percentileFilter must be 1-99");
		}

		
		_conn                   = conn;
		_percentileFilter       = percentileFilter;
		_hoursOfHistory         = hoursOfHistory;

		_criticalThresholdHours = criticalThresholdHours;
		_warningThresholdHours  = warningThresholdHours;
	}
	////////////////////////////////////////////////////////
	// END: Constructors
	////////////////////////////////////////////////////////
	

	public int     getPercentileFilter                 () { return _percentileFilter;       }
	public int     getHoursOfHistory                   () { return _hoursOfHistory;         }
	public int     getCriticalThresholdHours           () { return _criticalThresholdHours; }
	public int     getWarningThresholdHours            () { return _warningThresholdHours;  }
	public double  getFormatMbLessThanMbUsingOneDecimal() { return _formatMbLessThanMbUsingOneDecimal;  }
	public boolean getCreateSparkLines                 () { return _createSparkLines;       }
	public int     getSparkLineGroupDataByMinutes      () { return _sparkLineGroupDataByMinutes; }
	
	public SpaceFullPredictor setPercentileFilter                  (int     percentileFilter      ) { _percentileFilter                   = percentileFilter;           return this; }
	public SpaceFullPredictor setHoursOfHistory                    (int     hoursOfHistory        ) { _hoursOfHistory                     = hoursOfHistory;             return this; }
	public SpaceFullPredictor setDaysOfHistory                     (int     daysOfHistory         ) { _hoursOfHistory                     = daysOfHistory         * 24; return this; }
	public SpaceFullPredictor setCriticalThresholdHours            (int     criticalThresholdHours) { _criticalThresholdHours             = criticalThresholdHours;     return this; }
	public SpaceFullPredictor setCriticalThresholdDays             (int     criticalThresholdDays ) { _criticalThresholdHours             = criticalThresholdDays * 24; return this; }
	public SpaceFullPredictor setWarningThresholdHours             (int     warningThresholdHours ) { _warningThresholdHours              = warningThresholdHours;      return this; }
	public SpaceFullPredictor setWarningThresholdDays              (int     warningThresholdDays  ) { _warningThresholdHours              = warningThresholdDays  * 24; return this; }
	public SpaceFullPredictor setFormatMbLessThanMbUsingOneDecimal (double  mb                    ) { _formatMbLessThanMbUsingOneDecimal  = mb;                         return this; }
	public SpaceFullPredictor setCreateSparkLines                  (boolean createSparkLines      ) { _createSparkLines                   = createSparkLines;           return this; }
	public SpaceFullPredictor setSparkLineGroupDataByMinutes       (int     groupByMinutes        ) { _sparkLineGroupDataByMinutes        = groupByMinutes;             return this; }
	
	/**
	 * Is the Source Data in KB or MB
	 */
	public enum SourceDataSize
	{
		KB, // Use if the column names are in KB
		MB, // Use if the column names are in MB... 
		NONE // Do not know
	};
	
	/**
	 * Format a LocalDateTime as "YYYY-MM-DD HH:mm"
	 */
	private static String formatTimestamp(LocalDateTime dt)
	{
		return dt != null ? dt.format(TIMESTAMP_FORMATTER) : "-";
	}

	/**
	 * Prediction result containing all relevant information
	 */
	public class PredictionResult
	{
		public String        _resourceName;           // Filesystem or DB name
		public String        _secondaryName;          // Anything extra, could be 'FileSystemName' or 'DATA|LOG|WAL' (for a DBMS)
//		public long          _currentFreeKB;          // Current free/available space
//		public long          _currentUsedKB;          // Current used space
//		public long          _totalSizeKB;            // Total size (used + available)
		public double        _currentFreeKB;          // Current free/available space
		public double        _currentUsedKB;          // Current used space
		public double        _totalSizeKB;            // Total size (used + available)
		public double        _usedPct;                // Current usage percentage
		public double        _growthRateKBPerHour;    // KB growth per hour
		public double        _growthRateMBPerDay;     // MB growth per day
		public LocalDateTime _predictedFullTime;      // When it will be full
		public long          _hoursUntilFull;         // Hours until full
		public double        _rSquared;               // Regression quality (0-1)
		public int           _dataPointsUsed;         // Number of data points
		public boolean       _hasSufficientData;      // Enough data for prediction
		public String        _warningLevel;           // CRITICAL, WARNING, OK
		
		// Min/Max/Low-Peak statistics for available space
//		public long          _minAvailableMB;         // Minimum available MB seen
//		public long          _maxAvailableMB;         // Maximum available MB seen
//		public long          _lowPeakAvailableMB;     // Low peak (25th percentile)
		public double        _minAvailableMB;         // Minimum available MB seen
		public double        _maxAvailableMB;         // Maximum available MB seen
		public double        _lowPeakAvailableMB;     // Low peak (25th percentile)
		public LocalDateTime _lowPeakTime;            // When low peak occurred
		
		List<ITsDataPoint>    _tsDataUsedKb;
		List<ITsDataPoint>    _tsDataFreeKb;

		public String        _colLabelName;
		public String        _colLabelSecondName;
		
		public String getColnameResource()    { return StringUtil.isNullOrBlank(_colLabelName)       ? "Resource" : escapeHtml(_colLabelName);       }
		public String getColnameSecondary()   { return StringUtil.isNullOrBlank(_colLabelSecondName) ? "Named"    : escapeHtml(_colLabelSecondName); }

		public String getFmtResourceName()    { return escapeHtml(_resourceName); }
		public String getFmtSecondaryName()   { return escapeHtml(_secondaryName); }
		public String getFmtStatus()          { return escapeHtml(_hasSufficientData ? _warningLevel : NO_DATA); }
		public String getFmtUsedPct()         { return String.format("%.1f%%", _usedPct); }
		public String getFmtSizeMb()          { return formatMb(_totalSizeKB   / 1024.0); }
		public String getFmtUsedMb()          { return formatMb(_currentUsedKB / 1024.0); }
		public String getFmtFreeMb()          { return formatMb(_currentFreeKB / 1024.0); }
		public String getFmtSizeGb()          { return formatMb(_totalSizeKB   / 1024.0 / 1024.0 ); }
		public String getFmtUsedGb()          { return formatMb(_currentUsedKB / 1024.0 / 1024.0 ); }
		public String getFmtFreeGb()          { return formatMb(_currentFreeKB / 1024.0 / 1024.0 ); }
		public String getFmtMinFreeMb()       { return formatMb(_minAvailableMB); }
		public String getFmtMaxFreeMb()       { return formatMb(_maxAvailableMB); }
		public String getFmtLowPeakMb()       { return formatMb(_lowPeakAvailableMB); }
		public String getFmtLowPeakTime()     { return formatTimestamp(_lowPeakTime); }
		public String getFmtGrowthKbPerHour() { return String.format("%.1f", _growthRateKBPerHour); }
		public String getFmtGrowthMbPerDay()  { return formatMb(_growthRateMBPerDay); }
		public String getFmtGrowthGbPerDay()  { return formatMb(_growthRateMBPerDay / 1024.0); }
		public String getFmtHoursUntilFull()  { return _growthRateKBPerHour <= 0 ? "&infin;" : String.format("%,d",  _hoursUntilFull); }
		public String getFmtDaysUntilFull()   { return _growthRateKBPerHour <= 0 ? "&infin;" : String.format("%,d",  _hoursUntilFull / 24); }
		public String getFmtPredictFullTime() { return _growthRateKBPerHour <= 0 ? "Stable/Decreasing" : formatTimestamp(_predictedFullTime); }
		public String getFmtRSquared()        { return String.format("%.3f", _rSquared); }
		public String getFmtDataPoints()      { return String.format("%,d", _dataPointsUsed); }
		
		public String getFmtResourceAndSecondaryNamePlainStr() 
		{
			String retStr = getColnameResource() + "='" + _resourceName + "'";
			if (StringUtil.hasValue(_secondaryName))
				retStr += ", " + getColnameSecondary() + "='" + _secondaryName + "'";
				
			return retStr; 
		}

//		public String getSparcLineUsedMb()    { return "-not-yet-implemented-"; }
//		public String getSparcLineFreeMb()    { return "-not-yet-implemented-"; }

		public String getSparcLineUsedMb(Map<String, String> jsScriptOutMap)
		{
			// Create analyzer with 10-minute intervals
			TimeSeriesAnalyzer analyzer = new TimeSeriesAnalyzer( getSparkLineGroupDataByMinutes() );
			List<AggregatedDataPoint> aggregated = analyzer.aggregateWithAdjustment(_tsDataUsedKb, 1024.0);
			
			String htmlDivClassPrefix = "size-predict-sparkline";
			String htmlDivClassName   = "max-dataUsed";
			String divStr = analyzer.generateSparklineDivAndJs(aggregated, jsScriptOutMap, htmlDivClassPrefix, htmlDivClassName, SparklineType.MAX, 350, "Max Data Size Used In MB");

			return divStr;
		}
		public String getSparcLineFreeMb(Map<String, String> jsScriptOutMap)
		{
			// Create analyzer with 10-minute intervals
			TimeSeriesAnalyzer analyzer = new TimeSeriesAnalyzer( getSparkLineGroupDataByMinutes() );
			List<AggregatedDataPoint> aggregated = analyzer.aggregateWithAdjustment(_tsDataFreeKb, 1024.0);

			String htmlDivClassPrefix = "size-predict-sparkline";
			String htmlDivClassName   = "min-dataFree";
			String divStr = analyzer.generateSparklineDivAndJs(aggregated, jsScriptOutMap, htmlDivClassPrefix, htmlDivClassName, SparklineType.MIN, 350, "Min Data Size Free In MB");

			return divStr;
		}

		@Override
		public String toString()
		{
			StringBuilder sb = new StringBuilder();
			sb.append(getColnameResource() + ": ").append(getFmtResourceName()).append("\n");
			if (StringUtil.hasValue(getFmtSecondaryName()))
				sb.append(getColnameSecondary() + ": ").append(getFmtSecondaryName()).append("\n");
			sb.append("Current Usage: ").append(getFmtUsedPct())
				.append(" (").append(getFmtUsedMb()).append(" MB used, ")
				.append(getFmtFreeMb()).append(" MB available, ")
				.append(getFmtSizeMb()).append(" MB total)\n");
			
			if (!_hasSufficientData)
			{
				sb.append("Status: Insufficient data for prediction\n");
				return sb.toString();
			}
			
			sb.append("Available Space Stats: Min=").append(getFmtMinFreeMb())
				.append(" MB, Max=").append(getFmtMaxFreeMb())
				.append(" MB, Low-Peak=").append(getFmtLowPeakMb()).append(" MB");
			if (_lowPeakTime != null)
			{
				sb.append(" at ").append(getFmtLowPeakTime());
			}
			sb.append("\n");
			
			sb.append("Growth Rate: ").append(getFmtGrowthMbPerDay()).append(" MB/day")
				.append(" (").append(getFmtGrowthKbPerHour()).append(" KB/hour").append(")\n");
			sb.append("Prediction Quality (R²): ").append(getFmtRSquared()).append("\n");
			
			if (_growthRateKBPerHour <= 0)
			{
				sb.append("Status: Space usage is stable or decreasing\n");
			}
			else if (_hoursUntilFull < 0)
			{
				sb.append("Status: Unable to predict (negative timeline)\n");
			}
			else
			{
				sb.append("Predicted Full: ").append(getFmtPredictFullTime()).append("\n");
				sb.append("Time Until Full: ").append(getFmtHoursUntilFull()).append(" hours (")
					.append(getFmtDaysUntilFull()).append(" days)\n");
				sb.append("Warning Level: ").append(getFmtStatus()).append("\n");
			}
			
			return sb.toString();
		}

		/**
		 * Create a HTML Table from a ResultSetTableModel.<br>
		 * The parameter 'rowSpec' will create one row in the created table for each columns fetched from the 'sourceRstm'.
		 * 
		 * @param htmlClassname Table className
		 * @return
		 */
		public String toHtmlKeyValueTable(String htmlClassname)
		{
			LinkedHashMap<String, String> map = new LinkedHashMap<>();

			map.put(getColnameResource(), getFmtResourceName());

			if (StringUtil.hasValue(getFmtSecondaryName()))
				map.put(getColnameSecondary(), getFmtSecondaryName());

			map.put("Status"           , getFmtStatus());
			map.put("Used %"           , getFmtUsedPct());
			map.put("Size (MB)"        , getFmtSizeMb());
			map.put("Used (MB)"        , getFmtUsedMb());
			map.put("Free (MB)"        , getFmtFreeMb());
			map.put("Min Free (MB)"    , getFmtMinFreeMb());
			map.put("Max Free (MB)"    , getFmtMaxFreeMb());
			map.put("Low Peak (MB)"    , getFmtLowPeakMb());
			map.put("Low Peak Time"    , getFmtLowPeakTime());
			map.put("Growth (MB/day)"  , getFmtGrowthMbPerDay());
			map.put("Hours Until Full" , getFmtHoursUntilFull());
			map.put("Predict Full Time", getFmtPredictFullTime());
			map.put("R²"               , getFmtRSquared());
			map.put("Data Points"      , getFmtDataPoints());

			return StringUtil.toHtmlTable(map);
		}
	}
	
	private static class NamedDataSet
	{
		public NamedDataSet(String name, String secondName, LocalDateTime startTime)
		{
			_name       = name;
			_secondName = secondName;
			_startTime  = startTime;
		}
		
		String                     _name;
		String                     _secondName;
		LocalDateTime              _startTime;

		// Keep All data as a "TimeSerie" for USED and FREE
		List<ITsDataPoint>         _tsDataUsedKb     = new ArrayList<>();
		List<ITsDataPoint>         _tsDataFreeKb     = new ArrayList<>();
		
		List<HourDataPoint>        _rawData          = new ArrayList<>();
//		Map<Long, LocalDateTime>   _availableHistory = new HashMap<>();
//		long                       _currentUsedKB    = 0;
//		long                       _currentFreeKB    = 0;
//		long                       _sizeKB           = 0;
//		long                       _minAvailableKB   = Long.MAX_VALUE;
//		long                       _maxAvailableKB   = Long.MIN_VALUE;
		Map<Double, LocalDateTime> _availableHistory = new HashMap<>();
		double                     _currentUsedKB    = 0;
		double                     _currentFreeKB    = 0;
		double                     _sizeKB           = 0;
		double                     _minAvailableKB   = Double.MAX_VALUE;
		double                     _maxAvailableKB   = Double.MIN_VALUE;
		String                     _colLabelName;
		String                     _colLabelSecondName;
		
//		PredictionResult           _result;
	}

	/**
	 * Predicts when some name/resource will become full
	 * 
	 * @param conn
	 * @param sql -- SQL Must return the following ResultSet
	 *               <ol>
	 *               	<li>String    -- Which is some kind of name</li>
	 *               	<li>String    -- Which is a extra/secondary name (could be: NULL or 'file system name' or 'DATA|WAL|LOG' for a DBMS)</li>
	 *               	<li>Timestamp -- When the sample was done</li>
//	 *               	<li>int/long  -- Total Size in KB</li>
//	 *               	<li>int/long  -- Used  Size in KB</li>
//	 *               	<li>int/long  -- Free  Size in KB</li>
	 *               	<li>double    -- Total Size in KB</li>
	 *               	<li>double    -- Used  Size in KB</li>
	 *               	<li>double    -- Free  Size in KB</li>
	 *               </ol>
	 *               AND also ORDER BY 
	 * @return
	 */
	public Set<PredictionResult> predictSpaceFull(String sql)
	throws SQLException
	{
		int percentileFilter = getPercentileFilter();

		// Keep data for each "name" (size group)
		LinkedHashMap<String, NamedDataSet> nameDataSet = new LinkedHashMap<>();

//System.out.println("SQL=" + sql);

		if (_logger.isDebugEnabled())
			_logger.debug("predictSpaceFull(): SQL: " + sql);

		try (Statement stmnt = _conn.createStatement())
		{
			stmnt.setQueryTimeout(0);
			
			try (ResultSet rs = stmnt.executeQuery(sql))
			{
				// Check ResultSet if it looks OK
				ResultSetMetaData rsmd = rs.getMetaData();

				int expectedColCount = 6;
				if (rsmd.getColumnCount() != expectedColCount)
				{
					throw new SQLException("Expected " + expectedColCount + " columns (String, String, Timestamp, Number, Number, Number). Received columns was " + rsmd.getColumnCount());
				}

				int nameDataType       = rsmd.getColumnType(1);
				int secondNameDataType = rsmd.getColumnType(2);
				int timestampDataType  = rsmd.getColumnType(3);
				int totalKBDataType    = rsmd.getColumnType(4);
				int usedKBDataType     = rsmd.getColumnType(5);
				int freeKBDataType     = rsmd.getColumnType(6);

				if ( ! ResultSetTableModel.isStringDataType   (nameDataType      )) throw new SQLException("Expected Column 1 (name) to be some kind of String."          + " Received columns JDBC Type was " + ResultSetTableModel.getColumnJavaSqlTypeName(nameDataType));
				if ( ! ResultSetTableModel.isStringDataType   (secondNameDataType)) throw new SQLException("Expected Column 2 (second name) to be some kind of String."  + " Received columns JDBC Type was " + ResultSetTableModel.getColumnJavaSqlTypeName(secondNameDataType));
				if ( ! ResultSetTableModel.isTimestampDataType(timestampDataType )) throw new SQLException("Expected Column 3 (timestamp) to be some kind of Timestamp." + " Received columns JDBC Type was " + ResultSetTableModel.getColumnJavaSqlTypeName(timestampDataType));
				if ( ! ResultSetTableModel.isNumberDataType   (totalKBDataType   )) throw new SQLException("Expected Column 4 (totalKB) to be some kind of Number."      + " Received columns JDBC Type was " + ResultSetTableModel.getColumnJavaSqlTypeName(totalKBDataType));
				if ( ! ResultSetTableModel.isNumberDataType   (usedKBDataType    )) throw new SQLException("Expected Column 5 (usedKB) to be some kind of Number."       + " Received columns JDBC Type was " + ResultSetTableModel.getColumnJavaSqlTypeName(usedKBDataType));
				if ( ! ResultSetTableModel.isNumberDataType   (freeKBDataType    )) throw new SQLException("Expected Column 6 (freeKB) to be some kind of Number."       + " Received columns JDBC Type was " + ResultSetTableModel.getColumnJavaSqlTypeName(freeKBDataType));
				
				String colLabelName       = rsmd.getColumnLabel(1);
				String colLabelSecondName = rsmd.getColumnLabel(2);

				while (rs.next())
				{
					String    name       = rs.getString   (1);
					String    secondName = rs.getString   (2);
					Timestamp ts         = rs.getTimestamp(3);
//					long      totalKB    = rs.getLong     (4);
//					long      usedKB     = rs.getLong     (5);
//					long      freeKB     = rs.getLong     (6);
					double    totalKB    = rs.getDouble   (4);
					double    usedKB     = rs.getDouble   (5);
					double    freeKB     = rs.getDouble   (6);

					// Get the correct "slot" -- if not found create one!
					NamedDataSet dataset = nameDataSet.computeIfAbsent(name, (key) -> new NamedDataSet(name, secondName, ts.toLocalDateTime()));
					
					if (_createSparkLines)
					{
						dataset._tsDataUsedKb.add(new TsDataPoint(ts, usedKB));
						dataset._tsDataFreeKb.add(new TsDataPoint(ts, freeKB));
					}
					
					LocalDateTime sampleTime = ts.toLocalDateTime();
					long hoursSinceStart = ChronoUnit.HOURS.between(dataset._startTime, sampleTime);

					dataset._rawData.add(new HourDataPoint(hoursSinceStart, usedKB));
					dataset._availableHistory.put(freeKB, sampleTime);

					if (freeKB < dataset._minAvailableKB) dataset._minAvailableKB = freeKB;
					if (freeKB > dataset._maxAvailableKB) dataset._maxAvailableKB = freeKB;

					dataset._currentUsedKB = usedKB;
					dataset._currentFreeKB = freeKB;
					dataset._sizeKB        = totalKB;

					dataset._colLabelName       = colLabelName;
					dataset._colLabelSecondName = colLabelSecondName;
				}
			}
		}

		/*
		 * Why linear regression is used instead of simple (last - first) / time:
		 *
		 * 1. DBMS growth is bursty:
		 *    - Index rebuilds
		 *    - Bulk loads
		 *    - Autogrowth events
		 *    - Log truncation
		 *
		 * 2. A single delta between two samples is extremely sensitive to:
		 *    - Sampling interval
		 *    - One-time maintenance operations
		 *    - Measurement jitter
		 *
		 * 3. Least-squares regression:
		 *    - Uses all historical points
		 *    - Averages out short-term spikes and drops
		 *    - Produces a statistically stable long-term growth rate
		 *
		 * The resulting slope (KB/hour) represents the best linear approximation
		 * of sustained storage consumption and is therefore more suitable for
		 * forward extrapolation than point-to-point deltas.
		 */

		/*
		 * DBMS caveats -- Especially for SQL Server (because space inside the files can grow/shrink AND the files can be do "autogrow":
		 *
		 * - Autogrowth events change total size in steps, not continuously.
		 * - Log files can shrink after backup/truncate, temporarily inverting slope.
		 * - Small databases may show quantization effects (MB-level reporting).
		 * - A near-zero slope can explode the "hours until full" estimate.
		 *
		 * Therefore:
		 *   - Ignore predictions when slope <= epsilon.
		 *   - Treat results as trend indicators, not guarantees.
		 */
		
		// This is what we will return;
		Set<PredictionResult> returnResult = new LinkedHashSet<>();

		// Loop each of the data sets and create the Prediction
		for (NamedDataSet namedEntry : nameDataSet.values())
		{
			PredictionResult result = new PredictionResult();

			returnResult.add(result);
//			namedEntry._result = result;
			
			result._resourceName       = namedEntry._name;
			result._secondaryName      = namedEntry._secondName;
			result._currentUsedKB      = namedEntry._currentUsedKB;
			result._currentFreeKB      = namedEntry._currentFreeKB;
			result._totalSizeKB        = namedEntry._sizeKB;
			result._usedPct            = namedEntry._sizeKB > 0 ? (namedEntry._currentUsedKB * 100.0 / namedEntry._sizeKB) : 0.0;
			result._dataPointsUsed     = namedEntry._rawData.size();
			result._hasSufficientData  = namedEntry._rawData.size() >= 10;
			
			result._minAvailableMB     = namedEntry._minAvailableKB / 1024;
			result._maxAvailableMB     = namedEntry._maxAvailableKB / 1024;
			
			result._tsDataUsedKb       = namedEntry._tsDataUsedKb;
			result._tsDataFreeKb       = namedEntry._tsDataFreeKb;

			result._colLabelName       = namedEntry._colLabelName;
			result._colLabelSecondName = namedEntry._colLabelSecondName;
			
			
//			List<Long> availableValues = new ArrayList<>(namedEntry._availableHistory.keySet());
			List<Double> availableValues = new ArrayList<>(namedEntry._availableHistory.keySet());
			Collections.sort(availableValues);
			if (!availableValues.isEmpty())
			{
				int lowPeakIndex = (int) (0.25 * availableValues.size());
				if (lowPeakIndex >= availableValues.size()) 
					lowPeakIndex = availableValues.size() - 1;
//				long lowPeakValue = availableValues.get(lowPeakIndex);
				double lowPeakValue = availableValues.get(lowPeakIndex);
				result._lowPeakAvailableMB = lowPeakValue / 1024;
				result._lowPeakTime        = namedEntry._availableHistory.get(lowPeakValue);
			}

			if (result._hasSufficientData)
			{
//				Map<Long, List<Long>> hourlyData = new HashMap<>();
				Map<Long, List<Double>> hourlyData = new HashMap<>();
				for (HourDataPoint dp : namedEntry._rawData)
				{
					hourlyData.computeIfAbsent(dp._hoursSinceStart, k -> new ArrayList<>()).add(dp._usedKB);
				}
				
				List<HourDataPoint> filteredData = new ArrayList<>();
//				for (Map.Entry<Long, List<Long>> hourEntry : hourlyData.entrySet())
				for (Map.Entry<Long, List<Double>> hourEntry : hourlyData.entrySet())
				{
//					List<Long> values = hourEntry.getValue();
					List<Double> values = hourEntry.getValue();
					Collections.sort(values);
					
					int percentileIndex = (int) ((percentileFilter / 100.0) * values.size());
					if (percentileIndex >= values.size()) 
						percentileIndex = values.size() - 1;

//					long percentileValue = values.get(percentileIndex);
					double percentileValue = values.get(percentileIndex);
					filteredData.add(new HourDataPoint(hourEntry.getKey(), percentileValue));
				}
				
				LinearRegressionResult regression = calculateLinearRegression(filteredData);
				
				result._growthRateKBPerHour = regression._slope;
				result._growthRateMBPerDay = (regression._slope * 24) / 1024.0;
				result._rSquared = regression._rSquared;
				
				if (regression._slope > 0)
				{
//					result._hoursUntilFull    = (long) (namedEntry._currentFreeKB / regression._slope);
					result._hoursUntilFull    = Math.round(regression._slope > EPSILON ? (namedEntry._currentFreeKB / regression._slope) : Double.POSITIVE_INFINITY);
//					result._hoursUntilFull    = Math.min(result._hoursUntilFull, Integer.MAX_VALUE);
					result._hoursUntilFull    = Math.min(result._hoursUntilFull, 9_999_999);
					result._predictedFullTime = LocalDateTime.now().plusHours(result._hoursUntilFull);
					
					if (result._hoursUntilFull < getCriticalThresholdHours())
					{
						result._warningLevel = CRITICAL;
					}
					else if (result._hoursUntilFull < getWarningThresholdHours())
					{
						result._warningLevel = WARNING;
					}
					else
					{
						result._warningLevel = OK;
					}
				}
				else
				{
					result._hoursUntilFull = -1;
					result._warningLevel = OK;
				}
			}
		}
		
		return returnResult;
	}

	/**
	 * Prediction result containing all relevant information
	 * <p>
	 * The names should be in plain naming (quoted identifiers will be added to the names)
	 * <p>
	 * <ul>
	 *   <li>The column names will be prefix/suffix with '[' and ']'</li>
	 *   <li>If you have any '[' character in any of the column name, it will NOT prefix/suffix the columns with '[' and ']' </li>
	 *   <li>The square brackets will be translated into DBMS specific Quoted Chars. <br>
	 *       so: <code>[name]</code> may be translated into <code>"name"</code></li>
	 *   <li>If you want to combine several 'names', you can do that using: <code>[name]||' -- '||[name2]</code><br>
	 *       Note: The '||' will be replaced with '+' on vendors that do not support ANSI SQL Concatenation '||'</li>
	 *   <li>If the columns names holds data in MB, then use 'srcDataSize=SourceDataSize.MB'...<br> 
	 *       Column names will then be modified to <code>[sizeMb] * 1024</code> </li>
	 * </ul>
	 * 
	 * @param srcDataSize      KB or MB
	 * @param nameCol          Column Name of the resource
	 * @param secondNameCol    Column Name of the extra/secondary name for a resource (could be: null, 'file system name', or 'DATA|WAL|LOG' for a DBMS)
	 * @param timestampCol     Column name holding the timestamp the data was sampled
	 * @param totalSizeCol     Column name holding "total" size of the resource
	 * @param usedSizeCol      Column name holding "used" size of the resource
	 * @param freeSizeCol      Column name holding "free" size of the resource
	 * @param schemaName       Schema name of the table (can be null)
	 * @param tableName        Table name to search
	 * @return
	 * @throws SQLException
	 */
	public Set<PredictionResult> predictSpaceFull(
		 SourceDataSize srcDataSize
		,String nameCol
		,String secondNameCol
		,String timestampCol
		,String totalSizeCol
		,String usedSizeCol
		,String freeSizeCol
		,String schemaName
		,String tableName
	)
	throws SQLException
	{
		int hoursOfHistory = getHoursOfHistory();

		String aliasNameCol       = "";
		String aliasSecondNameCol = "";
		
		// Construct COLUMN Names
		if ( ! nameCol      .contains("[") ) { nameCol       = "[" + nameCol       + "]"; aliasNameCol = " AS " + nameCol; }
		if ( ! timestampCol .contains("[") ) { timestampCol  = "[" + timestampCol  + "]"; }
		if ( ! totalSizeCol .contains("[") ) { totalSizeCol  = "[" + totalSizeCol  + "]"; }
		if ( ! usedSizeCol  .contains("[") ) { usedSizeCol   = "[" + usedSizeCol   + "]"; }
		if ( ! freeSizeCol  .contains("[") ) { freeSizeCol   = "[" + freeSizeCol   + "]"; }

		if (StringUtil.hasValue(secondNameCol))
		{
			if ( ! secondNameCol.contains("[") && ! secondNameCol.contains("'"))
			{
				secondNameCol = "[" + secondNameCol + "]"; 
				aliasSecondNameCol = " AS " + secondNameCol;
			}
			else
			{
				aliasSecondNameCol = " AS [Info]";
			}
		}
		else
		{
			secondNameCol = "''";
		}

		// Construct TABLE Name
		String table = "[" + tableName + "]";
		if (StringUtil.hasValue(schemaName))
			table = "[" + schemaName + "]." + table;

		// Construct WHERE Clause
		String sqlWhere = "";
		if (hoursOfHistory > 0)
		{
			LocalDateTime startTime = LocalDateTime.now().minusHours(hoursOfHistory);
			Timestamp startTimestamp = Timestamp.valueOf(startTime);
			
			sqlWhere = "  AND " + timestampCol + " >= '" + startTimestamp + "' \n";
		}
		
		// if columns are in MB make it into KB
		String multiplyer = "";
		if (SourceDataSize.MB.equals(srcDataSize))
			multiplyer = " * 1024";

		String sql = ""
			+ "SELECT \n"
			+ "     " + nameCol       + aliasNameCol + " \n"
			+ "    ," + secondNameCol + aliasSecondNameCol + " \n"
			+ "    ," + timestampCol  + " AS [Ts] \n"
//			+ "    ,CAST(" + totalSizeCol + " AS BIGINT) " + multiplyer + " \n"
//			+ "    ,CAST(" + usedSizeCol  + " AS BIGINT) " + multiplyer + " \n"
//			+ "    ,CAST(" + freeSizeCol  + " AS BIGINT) " + multiplyer + " \n"
			+ "    ,(" + totalSizeCol + " * 1.0) " + multiplyer + " AS [TotalSizeKb] \n"
			+ "    ,(" + usedSizeCol  + " * 1.0) " + multiplyer + " AS [UsedSizeKb] \n"
			+ "    ,(" + freeSizeCol  + " * 1.0) " + multiplyer + " AS [FreeSizeKb] \n"
			+ "FROM " + table + " \n"
			+ "WHERE 1 = 1 \n"
			+ sqlWhere
			+ "ORDER BY \n"
			+ "     " + nameCol      + " \n"
			+ "    ," + timestampCol + " \n"
			;

		// Special considerations for Vendors
		if (_conn.isDatabaseProduct(DbUtils.DB_PROD_NAME_MSSQL))
		{
			// Most SQL Server Versions does not have '||' for concatenation, so use '+' instead
			sql = sql.replace("||", "+");
		}
		
		
		sql = _conn.quotifySqlString(sql);

		return predictSpaceFull(sql);
	}

	
	/**
	 * Generate a summary report sorted by urgency (plain text)
	 */
	public String generateReport(Set<PredictionResult> results)
	{
		return generateReport(new ArrayList<>(results));
	}

	/**
	 * Generate a summary report sorted by urgency (plain text)
	 */
	public String generateReport(List<PredictionResult> results)
	{
		results.sort((a, b) -> {
			if (!a._warningLevel.equals(b._warningLevel))
			{
				if (a._warningLevel.equals(CRITICAL)) return -1;
				if (b._warningLevel.equals(CRITICAL)) return 1;
				if (a._warningLevel.equals(WARNING))  return -1;
				if (b._warningLevel.equals(WARNING))  return 1;
			}
			return Long.compare(a._hoursUntilFull, b._hoursUntilFull);
		});
		
		StringBuilder report = new StringBuilder();
		report.append("================================================================================\n");
		report.append("DISK/DATABASE SPACE PREDICTION REPORT\n");
		report.append("Generated: ").append(formatTimestamp(LocalDateTime.now())).append("\n");
		report.append("================================================================================\n\n");
		
		long critical = results.stream().filter(r -> CRITICAL.equals(r._warningLevel)).count();
		long warning  = results.stream().filter(r -> WARNING .equals(r._warningLevel)).count();
		long ok       = results.stream().filter(r -> OK      .equals(r._warningLevel)).count();
		long insufficient = results.stream().filter(r -> !r._hasSufficientData).count();
		
		report.append("Summary:\n");
		report.append("  CRITICAL: ").append(critical    ).append("\n");
		report.append("  WARNING:  ").append(warning     ).append("\n");
		report.append("  OK:       ").append(ok          ).append("\n");
		report.append("  No Data:  ").append(insufficient).append("\n\n");
		
		for (PredictionResult result : results)
		{
			report.append("--------------------------------------------------------------------------------\n");
			report.append(result.toString());
			report.append("\n");
		}
		
		return report.toString();
	}
	
	/**
	 * Get HTML CSS for SpaceFullPredictor
	 */
	public static String getHtmlCss()
	{
		StringBuilder html = new StringBuilder();

		html.append("\n");
		html.append("  <!-- ################################### --> \n");
		html.append("  <!-- BEGIN Styles for SpaceFullPredictor --> \n");
		html.append("  <!-- ################################### --> \n");
		html.append("  <style> \n");
//		html.append("    .size-predict-summary          { background-color: #fff; padding: 15px; border-radius: 5px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); } \n");
		html.append("    .size-predict-summary          { background-color: #fff; padding: 4px; border-radius: 5px; margin-bottom: 5px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); } \n");
		html.append("    .size-predict-summary-item     { display: inline-block; margin-right: 30px; } \n");
		html.append("    .size-predict-summary-critical { color: #d32f2f; font-weight: bold; } \n");
		html.append("    .size-predict-summary-warning  { color: #f57c00; font-weight: bold; } \n");
		html.append("    .size-predict-summary-ok       { color: #388e3c; font-weight: bold; } \n");
		html.append("    .size-predict-summary-nodata   { color: #757575; font-weight: bold; } \n");
		html.append("    table.size-predict             { border-collapse: collapse; background-color: #fff; box-shadow: 0 2px 4px rgba(0,0,0,0.1); } \n");
		html.append("    table.size-predict th          { border: 1px solid black; background-color: #808080; color: white; padding: 4px; text-align: left; } \n");
//		html.append("    table.size-predict th:hover    { background-color: #1565c0; } \n");
		html.append("    table.size-predict td          { padding: 4px; border-bottom: 1px solid #ddd; } \n");
		html.append("    table.size-predict tr:hover    { background-color: #f5f5f5; } \n");
		html.append("    .size-predict-status-CRITICAL  { background-color: #ffebee; color: #c62828; font-weight: bold; } \n");
		html.append("    .size-predict-status-WARNING   { background-color: #fff3e0; color: #e65100; font-weight: bold; } \n");
		html.append("    .size-predict-status-OK        { background-color: #e8f5e9; color: #2e7d32; } \n");
		html.append("    .size-predict-status-NODATA    { background-color: #fafafa; color: #757575; } \n");
		html.append("    .size-predict-right-align      { text-align: right; } \n");
		html.append("    .size-predict-timestamp        { color: #757575; font-size: 0.9em; margin-bottom: 10px; } \n");

		html.append("    .size-predict-sparkline-wrapper {  \n");
		html.append("        position: relative; 			\n");
		html.append("        height:   19px					\n");
		html.append("    } \n");

		html.append("    .size-predict-sparkline-ind-val {  \n");
		html.append("        position:    absolute;			\n");
		html.append("        z-index:     2; 				\n");
		html.append("        left:        2px; 				\n");
		html.append("        top:         -2px; 			\n");
		html.append("        font-size:   9px;				\n");
		html.append("        font-family: Tahoma, Arial;	\n");
		html.append("        color:       black;			\n");
		html.append("        display:     none;				\n");
		html.append("    } \n");
		
		html.append("  </style> \n");
		html.append("  <!-- ################################### --> \n");
		html.append("  <!-- END Styles for SpaceFullPredictor --> \n");
		html.append("  <!-- ################################### --> \n");
		html.append("\n");

		return html.toString();
	}
	/**
	 * Get HTML CSS for SpaceFullPredictor
	 */
	public static String getHtmlJs()
	{
		StringBuilder html = new StringBuilder();

		// sorttable
		HtmlUtils.createJsScriptTag(html,
				"/scripts/sorttable/sorttable.js",
				"http://www.dbxtune.com/sorttable.js");
		
		// jquery
		HtmlUtils.createJsScriptTag(html,
				"/scripts/jquery/jquery-3.7.1.min.js", 
				"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js");
		
		// sparklines
		HtmlUtils.createJsScriptTag(html,
				"/scripts/jquery-sparklines/2.1.2/jquery.sparkline.min.js", 
				"https://cdnjs.cloudflare.com/ajax/libs/jquery-sparklines/2.1.2/jquery.sparkline.min.js");

		return html.toString();
	}

	/**
	 * Generate an HTML report with sortable, color-coded table
	 */
	public String generateHtmlReport(Set<PredictionResult> results, boolean fullPage, boolean printCss, String desciptionText)
	{
		return generateHtmlReport(new ArrayList<>(results), fullPage, printCss, desciptionText);
	}

//	/**
//	 * Generate an HTML report with sortable, color-coded table
//	 */
//	public String generateHtmlReport(List<PredictionResult> results, boolean fullPage, boolean printCss, String desciptionText)
//	{
//		// Set default description if none was passed.
//		if (StringUtil.isNullOrBlank(desciptionText)) 
//			desciptionText = "Disk/Database Space Prediction";
//
//		// If we create SparkLines -- We need to execute some JavaScript code... Lets put that in here
//		Map<String, String> jsScriptOutMap = new LinkedHashMap<>();
//		
//		results.sort((a, b) -> {
//			if (!a._warningLevel.equals(b._warningLevel))
//			{
//				if (a._warningLevel.equals(CRITICAL)) return -1;
//				if (b._warningLevel.equals(CRITICAL)) return 1;
//				if (a._warningLevel.equals(WARNING))  return -1;
//				if (b._warningLevel.equals(WARNING))  return 1;
//			}
//			return Long.compare(a._hoursUntilFull, b._hoursUntilFull);
//		});
//		
//		long critical     = results.stream().filter(r -> CRITICAL .equals(r._warningLevel)).count();
//		long warning      = results.stream().filter(r -> WARNING  .equals(r._warningLevel)).count();
//		long ok           = results.stream().filter(r -> OK       .equals(r._warningLevel)).count();
//		long insufficient = results.stream().filter(r -> !r._hasSufficientData).count();
//
//		StringBuilder html = new StringBuilder();
//		if (fullPage)
//		{
//    		html.append("<!DOCTYPE html> \n");
//    		html.append("<html> \n");
//    		html.append("<head> \n");
//    		html.append("  <meta charset='UTF-8'> \n");
//    		html.append("  <title>Disk/Database Space Prediction Report</title> \n");
//
//			html.append("  <style> \n");
//			html.append("    body { font-family: Arial, sans-serif; margin: 20px; background-color: #f5f5f5; } \n");
//			html.append("    h1 { color: #333; } \n");
//			html.append("  </style> \n");
//		}
//
//		if (printCss)
//		{
//			html.append( getHtmlCss() );
//			html.append( getHtmlJs() );
//		}
//
//		if (fullPage)
//		{
//			html.append("</head> \n");
//			html.append("<body> \n");
//
//			html.append("  <h1>").append(desciptionText).append("</h1>\n");
//			html.append("  <div class='size-predict-timestamp'>Generated: ").append(formatTimestamp(LocalDateTime.now())).append("</div> \n");
//		}
//		else 
//		{
//			html.append("  <b>").append(desciptionText).append("</b> \n");
//			html.append("  <br> \n");
//		}
//
//		// Output changes if we have any 'SecondaryName' -- Then we need to add 1 column
//		boolean hasSecondaryName = false;
//		for (PredictionResult pr : results)
//		{
//			if (StringUtil.hasValue(pr._secondaryName))
//			{
//				hasSecondaryName = true;
//				break;
//			}
//		}
//
//		//---------------------------------------
//		// Summary
//		//---------------------------------------
//		html.append("  <div class='size-predict-summary'> \n");
//		html.append("    <b>Summary: &nbsp; </b> \n");
//		html.append("    <div class='size-predict-summary-item'><span class='size-predict-summary-critical'>CRITICAL:</span> ").append(critical)    .append("</div> \n");
//		html.append("    <div class='size-predict-summary-item'><span class='size-predict-summary-warning' >WARNING: </span> ").append(warning)     .append("</div> \n");
//		html.append("    <div class='size-predict-summary-item'><span class='size-predict-summary-ok'      >OK:      </span> ").append(ok)          .append("</div> \n");
//		html.append("    <div class='size-predict-summary-item'><span class='size-predict-summary-nodata'  >No Data: </span> ").append(insufficient).append("</div> \n");
//		String criticalTheshold = getCriticalThresholdHours() < 24 ? getCriticalThresholdHours() + " hours" : getCriticalThresholdHours()/24 + " days";
//		String warningTheshold  = getWarningThresholdHours()  < 24 ? getWarningThresholdHours()  + " hours" : getWarningThresholdHours() /24 + " days";
//		html.append("    <div class='size-predict-summary-item'></div> \n"); // Just some extra space
//		html.append("    <div class='size-predict-summary-item'><span class='size-predict-summary-critical'>Critical Threshold:</span> ").append(criticalTheshold).append("</div> \n");
//		html.append("    <div class='size-predict-summary-item'><span class='size-predict-summary-warning' >Warning Threshold: </span> ").append(warningTheshold) .append("</div> \n");
//		html.append("  </div> \n");
//
//		
//		String resourceColName = "Resource";
//		String extraColName    = "Extra";
//		if ( ! results.isEmpty() )
//		{
//			resourceColName = results.get(0).getColnameResource();			
//			extraColName    = results.get(0).getColnameSecondary();
//		}
//		
//		//---------------------------------------
//		// Table output
//		//---------------------------------------
////		html.append("  <table class='sorttable'> \n");
//		html.append("  <table border=1 class='size-predict sortable'> \n");
//		html.append("    <thead> \n");
//		html.append("      <tr> \n");
//		html.append("        <th nowrap                                  title='Filesystem mount point or database name'>")                                        .append(resourceColName)      .append("</th> \n");
//		if (hasSecondaryName)
//		{
//			html.append("        <th nowrap                              title='Extra Name. Could be 'FileSystemName' or 'DATA|LOG|WAL' (for a DBMS)'>")           .append(extraColName)         .append("</th> \n");
//		}
//		html.append("        <th nowrap                                  title='Current status: CRITICAL, WARNING, OK, or NO DATA'>")                              .append("Status")             .append("</th> \n");
//		html.append("        <th nowrap class='size-predict-right-align' title='Current percentage of space used'>")                                               .append("Used %")             .append("</th> \n");
//		html.append("        <th nowrap class='size-predict-right-align' title='Total size of the filesystem or database in megabytes'>")                          .append("Size (MB)")          .append("</th> \n");
//		html.append("        <th nowrap class='size-predict-right-align' title='Current used space in megabytes'>")                                                .append("Used (MB)")          .append("</th> \n");
//		html.append("        <th nowrap class='size-predict-right-align' title='Current available/free space in megabytes'>")                                      .append("Free (MB)")          .append("</th> \n");
//		html.append("        <th nowrap class='size-predict-right-align' title='Minimum free space observed during the analysis period'>")                         .append("Min Free (MB)")      .append("</th> \n");
//		html.append("        <th nowrap class='size-predict-right-align' title='Maximum free space observed during the analysis period'>")                         .append("Max Free (MB)")      .append("</th> \n");
//		html.append("        <th nowrap class='size-predict-right-align' title='Low peak (25th percentile) of free space - helps identify typical low points'>")   .append("Low Peak (MB)")      .append("</th> \n");
//		html.append("        <th nowrap                                  title='Timestamp when the low peak free space occurred'>")                                .append("Low Peak Time")      .append("</th> \n");
//		html.append("        <th nowrap class='size-predict-right-align' title='Predicted growth rate in megabytes per day. \n\n * Positive = space growing (filling up), \n * Negative = space shrinking (freeing up), \n * Zero = stable'>").append("Growth (MB/day)").append("</th> \n");
//		html.append("        <th nowrap class='size-predict-right-align' title='Estimated hours until disk/database becomes full (based on current trend)'>")      .append("Hours Until Full")   .append("</th> \n");
//		html.append("        <th nowrap class='size-predict-right-align' title='Estimated days until disk/database becomes full'>")                                .append("Days Until Full")    .append("</th> \n");
//		html.append("        <th nowrap                                  title='Predicted date and time when space will be exhausted'>")                           .append("Predicted Full Time").append("</th> \n");
//		html.append("        <th nowrap class='size-predict-right-align' title='R-squared value (0-1) indicating prediction quality. \nHigher is more reliable.'>").append("R&sup2;")            .append("</th> \n");
//		html.append("        <th nowrap class='size-predict-right-align' title='Number of data points used in the prediction analysis'>")                          .append("Data Points")        .append("</th> \n");
//		if (_createSparkLines)
//		{
//			html.append("        <th nowrap                              title='Sparcline for UsedMb. Data is grouped by 10 minutes. See tooltip for details'>")   .append("Used MB Chart")      .append("</th> \n");
//			html.append("        <th nowrap                              title='Sparcline for FreeMb. Data is grouped by 10 minutes. See tooltip for details'>")   .append("Free MB Chart")      .append("</th> \n");
//		}
//		html.append("      </tr>\n");
//		html.append("    </thead> \n");
//		html.append("    <tbody> \n");
//
//		// Loop all records and print a "row"
//		for (PredictionResult result : results)
//		{
//			String statusClass = result._hasSufficientData ? "size-predict-status-" + result._warningLevel : "status-NODATA";
////			String statusText  = result._hasSufficientData ? result._warningLevel : NO_DATA;
//			
////			String name           = escapeHtml(result._resourceName);
////			String usedPct        = String.format("%.1f%%", result._usedPct);
//////			String sizeMb         = String.format("%,d", result._totalSizeKB   / 1024);
//////			String usedMb         = String.format("%,d", result._currentUsedKB / 1024);
//////			String freeMb         = String.format("%,d", result._currentFreeKB / 1024);
////			String sizeMb         = formatMb(result._totalSizeKB   / 1024.0);
////			String usedMb         = formatMb(result._currentUsedKB / 1024.0);
////			String freeMb         = formatMb(result._currentFreeKB / 1024.0);
////
////			String dataPoints     = "" + result._dataPointsUsed;
//			
//
//			html.append("      <tr class='").append(statusClass).append("'> \n");
//			html.append("        <td nowrap>")                                 .append( result.getFmtResourceName()  ).append("</td> \n");
//			if (hasSecondaryName) { html.append("        <td nowrap>")         .append( result.getFmtSecondaryName() ).append("</td> \n"); }
//			html.append("        <td nowrap>")                                 .append( result.getFmtStatus()        ).append("</td> \n");
//			html.append("        <td nowrap class='size-predict-right-align'>").append( result.getFmtUsedPct()       ).append("</td> \n");
//			html.append("        <td nowrap class='size-predict-right-align'>").append( result.getFmtSizeMb()        ).append("</td> \n");
//			html.append("        <td nowrap class='size-predict-right-align'>").append( result.getFmtUsedMb()        ).append("</td> \n");
//			html.append("        <td nowrap class='size-predict-right-align'>").append( result.getFmtFreeMb()        ).append("</td> \n");
//			
//			if (!result._hasSufficientData)
//			{
//				int numOfCells = _createSparkLines ? 12 : 10;   // 12 with SparkLines Enabled, else 10
//				html.append("        <td nowrap class='size-predict-right-align'>-</td>\n".repeat(numOfCells));
//			}
//			else
//			{
//				html.append("        <td nowrap class='size-predict-right-align'>").append( result.getFmtMinFreeMb()       ).append("</td> \n");
//				html.append("        <td nowrap class='size-predict-right-align'>").append( result.getFmtMaxFreeMb()       ).append("</td> \n");
//				html.append("        <td nowrap class='size-predict-right-align'>").append( result.getFmtLowPeakMb()       ).append("</td> \n");
//				html.append("        <td nowrap>"                                 ).append( result.getFmtLowPeakTime()     ).append("</td> \n");
//				html.append("        <td nowrap class='size-predict-right-align'>").append( result.getFmtGrowthMbPerDay()  ).append("</td> \n");
//				html.append("        <td nowrap class='size-predict-right-align'>").append( result.getFmtHoursUntilFull()  ).append("</td> \n");
//				html.append("        <td nowrap class='size-predict-right-align'>").append( result.getFmtDaysUntilFull()   ).append("</td> \n");
//				html.append("        <td nowrap>"                                 ).append( result.getFmtPredictFullTime() ).append("</td> \n");
//				html.append("        <td nowrap class='size-predict-right-align'>").append( result.getFmtRSquared()        ).append("</td> \n");
//			}
//			
//			html.append("        <td class='size-predict-right-align'>").append( result.getFmtDataPoints()   ).append("</td> \n");
//			if (_createSparkLines)
//			{
//    			html.append("        <td nowrap>"                          ).append( result.getSparcLineUsedMb(jsScriptOutMap) ).append("</td> \n");
//    			html.append("        <td nowrap>"                          ).append( result.getSparcLineFreeMb(jsScriptOutMap) ).append("</td> \n");
//			}
//			html.append("      </tr> \n");
//		}
//		
//		html.append("    </tbody> \n");
//		html.append("  </table> \n");
//
//		if (_createSparkLines)
//		{
//			html.append("\n");
//			html.append("  <!-- ########################### --> \n");
//			html.append("  <!-- Execute when page is LOADED --> \n");
//			html.append("  <!-- ########################### --> \n");
//			html.append("  <script> \n");
//			html.append("  window.addEventListener('load', () => \n");
//			html.append("  { \n");
//			html.append("      console.log('Page is loaded, now initializing, SparkLines...'); \n");
//// DEBUG: To defer it a bit
//html.append("      setTimeout(() => { \n");
//			for (String jsCode : jsScriptOutMap.values())
//			{
//				html.append(jsCode).append(" \n");
//			}
//			html.append("      // now show the Min|Max: ### indicator \n");
//			html.append("      $('.size-predict-sparkline-ind-val').css('display', 'block'); \n");
//html.append("      }, 1000); \n");
//			html.append("  }); \n");
//			html.append("  </script> \n");
//		}
//		
//		if (fullPage)
//		{
//			html.append("</body> \n");
//			html.append("</html> \n");
//		}
//
//		return html.toString();
//	}

	/**
	 * Generate an HTML report with sortable, color-coded table
	 */
	public String generateHtmlReport(List<PredictionResult> results, boolean fullPage, boolean printCss, String desciptionText)
	{
		// Set default description if none was passed.
		if (StringUtil.isNullOrBlank(desciptionText)) 
			desciptionText = "Disk/Database Space Prediction";

		// If we create SparkLines -- We need to execute some JavaScript code... Lets put that in here
		Map<String, String> jsScriptOutMap = new LinkedHashMap<>();
		
		results.sort((a, b) -> {
			if (!a._warningLevel.equals(b._warningLevel))
			{
				if (a._warningLevel.equals(CRITICAL)) return -1;
				if (b._warningLevel.equals(CRITICAL)) return 1;
				if (a._warningLevel.equals(WARNING))  return -1;
				if (b._warningLevel.equals(WARNING))  return 1;
			}
			// _hoursUntilFull == -1 >>means>> 'Stable/Decreasing'
//			return Long.compare(a._hoursUntilFull, b._hoursUntilFull);
			return Long.compare(
					a._hoursUntilFull == -1 ? Long.MAX_VALUE : a._hoursUntilFull,
					b._hoursUntilFull == -1 ? Long.MAX_VALUE : b._hoursUntilFull);
		});
		
		long critical     = results.stream().filter(r -> CRITICAL .equals(r._warningLevel)).count();
		long warning      = results.stream().filter(r -> WARNING  .equals(r._warningLevel)).count();
		long ok           = results.stream().filter(r -> OK       .equals(r._warningLevel)).count();
		long insufficient = results.stream().filter(r -> !r._hasSufficientData).count();

		StringBuilder html = new StringBuilder();
		if (fullPage)
		{
    		html.append("<!DOCTYPE html> \n");
    		html.append("<html> \n");
    		html.append("<head> \n");
    		html.append("  <meta charset='UTF-8'> \n");
    		html.append("  <title>Disk/Database Space Prediction Report</title> \n");

			html.append("  <style> \n");
			html.append("    body { font-family: Arial, sans-serif; margin: 20px; background-color: #f5f5f5; } \n");
			html.append("    h1 { color: #333; } \n");
			html.append("  </style> \n");
		}

		if (printCss)
		{
			html.append( getHtmlCss() );
			html.append( getHtmlJs() );
		}

		if (fullPage)
		{
			html.append("</head> \n");
			html.append("<body> \n");

			html.append("  <h1>").append(desciptionText).append("</h1>\n");
			html.append("  <div class='size-predict-timestamp'>Generated: ").append(formatTimestamp(LocalDateTime.now())).append("</div> \n");
		}
		else 
		{
			html.append("  <b>").append(desciptionText).append("</b> \n");
			html.append("  <br> \n");
		}

		// Output changes if we have any 'SecondaryName' -- Then we need to add 1 column
		boolean hasSecondaryName = false;
		for (PredictionResult pr : results)
		{
			if (StringUtil.hasValue(pr._secondaryName))
			{
				hasSecondaryName = true;
				break;
			}
		}

		//---------------------------------------
		// Summary
		//---------------------------------------
		html.append("  <div class='size-predict-summary'> \n");
		html.append("    <b>Summary: &nbsp; </b> \n");
//		html.append("    <div class='size-predict-summary-item'><span class='size-predict-summary-critical'>CRITICAL:</span> ").append(critical)    .append("</div> \n");
//		html.append("    <div class='size-predict-summary-item'><span class='size-predict-summary-warning' >WARNING: </span> ").append(warning)     .append("</div> \n");
//		html.append("    <div class='size-predict-summary-item'><span class='size-predict-summary-ok'      >OK:      </span> ").append(ok)          .append("</div> \n");
//		html.append("    <div class='size-predict-summary-item'><span class='size-predict-summary-nodata'  >No Data: </span> ").append(insufficient).append("</div> \n");
		html.append("    <div class='size-predict-summary-item'><span style='color: #d32f2f; font-weight: bold;'>CRITICAL:</span> ").append(critical)    .append("</div> \n");
		html.append("    <div class='size-predict-summary-item'><span style='color: #f57c00; font-weight: bold;'>WARNING: </span> ").append(warning)     .append("</div> \n");
		html.append("    <div class='size-predict-summary-item'><span style='color: #388e3c; font-weight: bold;'>OK:      </span> ").append(ok)          .append("</div> \n");
		html.append("    <div class='size-predict-summary-item'><span style='color: #757575; font-weight: bold;'>No Data: </span> ").append(insufficient).append("</div> \n");
		String criticalTheshold = getCriticalThresholdHours() + " hours <i>(" + getCriticalThresholdHours()/24 + " days)</i>";
		String warningTheshold  = getWarningThresholdHours()  + " hours <i>(" + getWarningThresholdHours() /24 + " days)</i>";
		html.append("    <div class='size-predict-summary-item'></div> \n"); // Just some extra space
		html.append("    <div class='size-predict-summary-item'><span class='size-predict-summary-critical'>Critical Threshold:</span> ").append(criticalTheshold).append("</div> \n");
		html.append("    <div class='size-predict-summary-item'><span class='size-predict-summary-warning' >Warning Threshold: </span> ").append(warningTheshold) .append("</div> \n");
		html.append("  </div> \n");

		
		String resourceColName = "Resource";
		String extraColName    = "Extra";
		if ( ! results.isEmpty() )
		{
			resourceColName = results.get(0).getColnameResource();			
			extraColName    = results.get(0).getColnameSecondary();
		}
		
		//---------------------------------------
		// Table output
		//---------------------------------------
//		html.append("  <table class='sorttable'> \n");
		html.append("  <table border=1 class='size-predict sortable'> \n");
		html.append("    <thead> \n");
		html.append("      <tr> \n");
		html.append("        <th nowrap title='Filesystem mount point or database name'>")                                         .append(resourceColName)      .append("</th> \n");
		if (hasSecondaryName)
		{
			html.append("        <th nowrap title='Extra Name. Could be 'FileSystemName' or 'DATA|LOG|WAL' (for a DBMS)'>")        .append(extraColName)         .append("</th> \n");
		}
		html.append("        <th nowrap title='Current status: CRITICAL, WARNING, OK, or NO DATA'>")                               .append("Status")             .append("</th> \n");
		html.append("        <th nowrap title='Current percentage of space used'>")                                                .append("Used %")             .append("</th> \n");
		html.append("        <th nowrap title='Estimated days until disk/database becomes full'>")                                 .append("Days Until Full")    .append("</th> \n");
		html.append("        <th nowrap title='Estimated hours until disk/database becomes full (based on current trend)'>")       .append("Hours Until Full")   .append("</th> \n");
		html.append("        <th nowrap title='Predicted date and time when space will be exhausted'>")                            .append("Predicted Full Time").append("</th> \n");
		html.append("        <th nowrap title='Total size of the filesystem or database in megabytes'>")                           .append("Size (MB)")          .append("</th> \n");
		html.append("        <th nowrap title='Current used space in megabytes'>")                                                 .append("Used (MB)")          .append("</th> \n");
		html.append("        <th nowrap title='Current available/free space in megabytes'>")                                       .append("Free (MB)")          .append("</th> \n");
		html.append("        <th nowrap title='Predicted growth rate in megabytes per day. \n\n * Positive = space growing (filling up), \n * Negative = space shrinking (freeing up), \n * Zero = stable'>").append("Growth (MB/day)").append("</th> \n");
		if (_createSparkLines)
		{
			html.append("        <th nowrap title='Sparcline for UsedMb. Data is grouped by 10 minutes. See tooltip for details'>").append("Used MB Chart")      .append("</th> \n");
			html.append("        <th nowrap title='Sparcline for FreeMb. Data is grouped by 10 minutes. See tooltip for details'>").append("Free MB Chart")      .append("</th> \n");
		}
		html.append("        <th nowrap title='Minimum free space observed during the analysis period'>")                          .append("Min Free (MB)")      .append("</th> \n");
		html.append("        <th nowrap title='Maximum free space observed during the analysis period'>")                          .append("Max Free (MB)")      .append("</th> \n");
//		html.append("        <th nowrap title='Low peak (25th percentile) of free space - helps identify typical low points'>")    .append("Low Peak (MB)")      .append("</th> \n");
//		html.append("        <th nowrap title='Timestamp when the low peak free space occurred'>")                                 .append("Low Peak Time")      .append("</th> \n");
		html.append("        <th nowrap title='R-squared value (0-1) indicating prediction quality. \nHigher is more reliable.'>") .append("R&sup2;")            .append("</th> \n");
		html.append("        <th nowrap title='Number of data points used in the prediction analysis'>")                           .append("Data Points")        .append("</th> \n");
		html.append("      </tr>\n");
		html.append("    </thead> \n");
		html.append("    <tbody> \n");

		// Loop all records and print a "row"
		for (PredictionResult result : results)
		{
//			String statusClass = result._hasSufficientData ? "size-predict-status-" + result._warningLevel : "status-NODATA";
			
			// The class thing did not work on IOS... don't know why... testing in-line styling instead
			String trStyle = "";
			if (CRITICAL.equals(result._warningLevel)) trStyle = "background-color: #ffebee; color: #c62828; font-weight: bold;";
			if (WARNING .equals(result._warningLevel)) trStyle = "background-color: #fff3e0; color: #e65100; font-weight: bold;";
			if (OK      .equals(result._warningLevel)) trStyle = "background-color: #e8f5e9; color: #2e7d32;";
			if (/*NODATA*/ !result._hasSufficientData) trStyle = "background-color: #fafafa; color: #757575;"; // NO_DATA

			// ???? -- Possibly use <td sorttable_customkey='999999'> for sorting on Hours/Days, when it's '&infin;'
			
			String ttSizeGb = "title='" + result.getFmtSizeGb()         + " GB'";
			String ttUsedGb = "title='" + result.getFmtUsedGb()         + " GB'";
			String ttFreeGb = "title='" + result.getFmtFreeGb()         + " GB'";
			String ttGrowGb = "title='" + result.getFmtGrowthGbPerDay() + " GB'";

			//			html.append("      <tr class='").append(statusClass).append("'> \n");
			html.append("      <tr style='").append(trStyle).append("'> \n");
			html.append("        <td nowrap>"                                           ).append( result.getFmtResourceName()    ).append("</td> \n");    // Resource
			if (hasSecondaryName) { html.append("        <td nowrap>"                   ).append( result.getFmtSecondaryName()   ).append("</td> \n"); }  // Extra/Info
			html.append("        <td nowrap>"                                           ).append( result.getFmtStatus()          ).append("</td> \n");    // Status
			html.append("        <td nowrap align='right'>"                             ).append( result.getFmtUsedPct()         ).append("</td> \n");    // Used Percent
			html.append("        <td nowrap align='right' sorttable_customkey='999999'>").append( result.getFmtDaysUntilFull()   ).append("</td> \n");    // Days Until Full
			html.append("        <td nowrap align='right' sorttable_customkey='999999'>").append( result.getFmtHoursUntilFull()  ).append("</td> \n");    // Hours Until Full
			html.append("        <td nowrap               sorttable_customkey='999999'>").append( result.getFmtPredictFullTime() ).append("</td> \n");    // Predicted Full Time
			html.append("        <td nowrap align='right' ").append(ttSizeGb).append(">").append( result.getFmtSizeMb()          ).append("</td> \n");    // Size MB
			html.append("        <td nowrap align='right' ").append(ttUsedGb).append(">").append( result.getFmtUsedMb()          ).append("</td> \n");    // Used MB
			html.append("        <td nowrap align='right' ").append(ttFreeGb).append(">").append( result.getFmtFreeMb()          ).append("</td> \n");    // Free MB
			html.append("        <td nowrap align='right' ").append(ttGrowGb).append(">").append( result.getFmtGrowthMbPerDay()  ).append("</td> \n");    // Growth (MB/day)
			if (_createSparkLines)
			{
    			html.append("        <td nowrap>"                                       ).append( result.getSparcLineUsedMb(jsScriptOutMap) ).append("</td> \n");    // Used MB Chart
    			html.append("        <td nowrap>"                                       ).append( result.getSparcLineFreeMb(jsScriptOutMap) ).append("</td> \n");    // Free MB Chart
			}
			html.append("        <td nowrap align='right'>"                             ).append( result.getFmtMinFreeMb()       ).append("</td> \n");    // Min Free MB
			html.append("        <td nowrap align='right'>"                             ).append( result.getFmtMaxFreeMb()       ).append("</td> \n");    // Max Free MB
//			html.append("        <td nowrap align='right'>"                             ).append( result.getFmtLowPeakMb()       ).append("</td> \n");    // Low Peak MB
//			html.append("        <td nowrap>"                                           ).append( result.getFmtLowPeakTime()     ).append("</td> \n");    // Low Peak Time
			html.append("        <td nowrap align='right'>"                             ).append( result.getFmtRSquared()        ).append("</td> \n");    // R-squared
			html.append("        <td nowrap align='right'>"                             ).append( result.getFmtDataPoints()      ).append("</td> \n");    // Data Points
			html.append("      </tr> \n");
		}
		
		html.append("    </tbody> \n");
		html.append("  </table> \n");

		if (_createSparkLines)
		{
			html.append("\n");
			html.append("  <!-- ########################### --> \n");
			html.append("  <!-- Execute when page is LOADED --> \n");
			html.append("  <!-- ########################### --> \n");
			html.append("  <script> \n");
			html.append("  window.addEventListener('load', () => \n");
			html.append("  { \n");
			html.append("      console.log('Page is loaded, now initializing, SparkLines...'); \n");
			
			// DEBUG: To defer it a bit using: setTimeout(() => { jsCodeThatInitializesAllSparkLines; }, 2000); 
			if (_logger.isDebugEnabled())
				html.append("      setTimeout(() => { \n");

			for (String jsCode : jsScriptOutMap.values())
			{
				html.append(jsCode).append(" \n");
			}
			html.append("      // now show the Min|Max: ### indicator \n");
			html.append("      $('.size-predict-sparkline-ind-val').css('display', 'block'); \n");
			
			// DEBUG: To defer it a bit
			if (_logger.isDebugEnabled())
				html.append("      }, 2000); \n");

			html.append("  }); \n");
			html.append("  </script> \n");
		}
		
		if (fullPage)
		{
			html.append("</body> \n");
			html.append("</html> \n");
		}

		return html.toString();
	}

	private String formatMb(double val)
	{
		double formatMbLessThanMbUsingOneDecimal = getFormatMbLessThanMbUsingOneDecimal();
		if (val < formatMbLessThanMbUsingOneDecimal)
		{
			return String.format("%.1f", val);
		}

		return String.format("%,.0f", val);		
	}
	
	private String escapeHtml(String text)
	{
		if (text == null) 
			return "";

		return text
				.replace("&", "&amp;")
				.replace("<",  "&lt;")
				.replace(">",  "&gt;")
				.replace("\"", "&quot;")
				.replace("'",  "&#39;");
	}
	
	/**
	 * Data point for regression analysis
	 */
	private static class HourDataPoint
	{
		long _hoursSinceStart;
//		long _usedKB;
		double _usedKB;
		
//		DataPoint(long hoursSinceStart, long usedKB)
		HourDataPoint(long hoursSinceStart, double usedKB)
		{
			this._hoursSinceStart = hoursSinceStart;
			this._usedKB = usedKB;
		}
	}
	
	@SuppressWarnings("unused")
	private static class LinearRegressionResult
	{
		double _slope;
		double _intercept;
		double _rSquared;
	}
	
	/**
	 * Performs simple least-squares linear regression on a set of (x, y) points.
	 *
	 * <p>The regression fits the model:</p>
	 * <pre>
	 *     y = a + b * x
	 * </pre>
	 *
	 * where:
	 * <ul>
	 *   <li>x = time in hours since the first observation</li>
	 *   <li>y = used disk space in KB</li>
	 *   <li>a = intercept (estimated used space at time zero)</li>
	 *   <li>b = slope (average growth rate in KB per hour)</li>
	 * </ul>
	 *
	 * <p>The slope is computed using the standard least-squares formula:</p>
	 * <pre>
	 *     b = Σ((xi - x̄)(yi - ȳ)) / Σ((xi - x̄)²)
	 * </pre>
	 *
	 * <p>This method minimizes the squared vertical error between the observed
	 * values and the fitted line, providing a stable estimate of long-term
	 * growth even in the presence of short-term noise (backups, index rebuilds,
	 * log truncation, etc.).</p>
	 *
	 * <p>Interpretation:</p>
	 * <ul>
	 *   <li>b &gt; 0  → disk is growing; can extrapolate time to full.</li>
	 *   <li>b ≈ 0  → no meaningful growth; prediction is unreliable.</li>
	 *   <li>b &lt; 0  → net shrinking; disk-full prediction is invalid.</li>
	 * </ul>
	 */
	private static LinearRegressionResult calculateLinearRegression(List<HourDataPoint> data)
	{
		int n = data.size();
		double sumX = 0, sumY = 0, sumXY = 0, sumX2 = 0;
		
		for (HourDataPoint dp : data)
		{
			sumX  += dp._hoursSinceStart;
			sumY  += dp._usedKB;
			sumXY += dp._hoursSinceStart * dp._usedKB;
			sumX2 += dp._hoursSinceStart * dp._hoursSinceStart;
		}
		
		double slope     = (n * sumXY - sumX * sumY) / (n * sumX2 - sumX * sumX);
		double intercept = (sumY - slope * sumX) / n;
		
		double meanY = sumY / n;
		double ssTotal = 0, ssResidual = 0;
		
		for (HourDataPoint dp : data)
		{
			double predicted = slope * dp._hoursSinceStart + intercept;
			ssTotal    += Math.pow(dp._usedKB - meanY, 2);
			ssResidual += Math.pow(dp._usedKB - predicted, 2);
		}
		
		double rSquared = ssTotal > 0 ? 1 - (ssResidual / ssTotal) : 0;
		
		LinearRegressionResult result = new LinearRegressionResult();
		result._slope     = slope;
		result._intercept = intercept;
		result._rSquared  = Math.max(0, Math.min(1, rSquared));
		
		return result;
	}
	
	public static Set<PredictionResult> getSeverityCriticals(Set<PredictionResult> predictions)
	{
		// Get CRITICAL Alerts
		Set<PredictionResult> critical = predictions.stream()
			.filter(r -> CRITICAL.equals(r._warningLevel))
			.collect(Collectors.toSet());

		return critical;
	}
	
	public static Set<PredictionResult> getSeverityWarnings(Set<PredictionResult> predictions)
	{
		// Get CRITICAL Alerts
		Set<PredictionResult> warnings = predictions.stream()
			.filter(r -> WARNING.equals(r._warningLevel))
			.collect(Collectors.toSet());

		return warnings;
	}
	
	public static Set<PredictionResult> getSeverityOk(Set<PredictionResult> predictions)
	{
		// Get CRITICAL Alerts
		Set<PredictionResult> ok = predictions.stream()
			.filter(r -> OK.equals(r._warningLevel))
			.collect(Collectors.toSet());

		return ok;
	}
	
	public static void main(String[] args)
	{
//		String url = "jdbc:h2:file:C:/Users/goran/.dbxtune/data/PROD_A2_ASE_2026-01-23;IFEXISTS=TRUE";
//		String url = "jdbc:h2:file:C:/Users/goran/.dbxtune/data/MM-OP-JVSDB_2026-01-22;IFEXISTS=TRUE";
//		String url = "jdbc:h2:file:C:/Users/goran/.dbxtune/data/MM-OP-JVSDB_2026-01-24;IFEXISTS=TRUE";
		String url = "jdbc:h2:file:C:/Users/goran/.dbxtune/data/MM-OP-JVSDB_2026-02-06;IFEXISTS=TRUE";

		try (Connection jdbcConn = DriverManager.getConnection(url, "sa", ""))
		{
			DbxConnection conn = DbxConnection.createDbxConnection(jdbcConn);

			SpaceFullPredictor spaceFullPredictor = new SpaceFullPredictor(conn)
					.setCriticalThresholdHours(DEFAULT_criticalThresholdHours)
					.setWarningThresholdHours (DEFAULT_warningThresholdHours)
					.setHoursOfHistory        (DEFAULT_hoursOfHistory)
					.setPercentileFilter      (DEFAULT_percentileFilter);
			
			Set<PredictionResult> allResults = new LinkedHashSet<>();

			//----------------
			System.out.println("Analyzing filesystems...");
			Set<PredictionResult> fsResult = spaceFullPredictor.predictSpaceFull(
					SourceDataSize.KB,
					"MountedOn", 
					"Filesystem", 
					"SessionSampleTime", 
					"Size-KB", 
					"Used-KB", 
					"Available-KB", 
					null, 
					"CmOsDiskSpace_abs");
			allResults.addAll(fsResult);

			boolean doDb = false;
			if (doDb)
			{
				//----------------
				System.out.println("Analyzing databases...");
				Set<PredictionResult> dbDataResult = spaceFullPredictor.predictSpaceFull(
						SourceDataSize.MB,
						"DBName",
						"'DATA'",
						"SessionSampleTime", 
						"DataSizeInMb",// "DbSizeInMb", 
						"DataSizeUsedInMb", 
						"DataSizeFreeInMb", 
						null, 
						"CmDatabases_abs");
				allResults.addAll(dbDataResult);

				Set<PredictionResult> dbWalResult = spaceFullPredictor.predictSpaceFull(
						SourceDataSize.MB,
						"DBName", 
						"'LOG'",
						"SessionSampleTime", 
						"LogSizeInMb", 
						"LogSizeUsedInMb", 
						"LogSizeFreeInMb", 
						null, 
						"CmDatabases_abs");
				allResults.addAll(dbWalResult);
			}
			
			// String Report
			String report = spaceFullPredictor.generateReport(allResults);
			System.out.println(report);
			
			// Html Report
			String htmlReport = spaceFullPredictor.generateHtmlReport(allResults, true, true, null);
			
			File htmlReportFile = new File("space_prediction_report.html");
			try (FileWriter writer = new FileWriter(htmlReportFile))
			{
				writer.write(htmlReport);
				System.out.println("\nHTML report saved to: " + htmlReportFile.getAbsolutePath());
			}
			catch (IOException e)
			{
				System.err.println("Error saving HTML report: " + e.getMessage());
			}
			
			// ALERTS to STDOUT
			Set<PredictionResult> severityCriticals = SpaceFullPredictor.getSeverityCriticals(allResults);
			Set<PredictionResult> severityWarnings  = SpaceFullPredictor.getSeverityWarnings (allResults);
			Set<PredictionResult> severityOk        = SpaceFullPredictor.getSeverityOk       (allResults);
			
			System.out.println("");
			System.out.println("Resources Severity Count: Criticals=" + severityCriticals.size() + ", Warnings=" + severityWarnings.size() + ", OK=" + severityOk.size() + ".");

//			if ( ! severityCriticals.isEmpty() )
			if ( severityCriticals.size() > 0 )
			{
				System.out.println("\n!!! CRITICAL ALERTS !!!");
				for (PredictionResult r : severityCriticals)
				{
					System.out.println("  - " + r._resourceName + " will be full in " + r._hoursUntilFull + " hours!");
				}
			}
			
			boolean sendEmail = true;
			sendEmail = false;
			if (sendEmail)
			{
				sendMail(htmlReport);
				
				openInBrowser(htmlReportFile);
			}
		}
		catch (SQLException e)
		{
			e.printStackTrace();
		}
	}
	
	
	/**
	 * Since we send mail from 2 places... use this to "create and setup" a basic email message
	 * 
	 * @param toList
	 * @return
	 * @throws EmailException
	 */
	private static void sendMail(String msgBody)
//	throws EmailException
	{
		try
		{
			HtmlEmail email = new HtmlEmail();

			String  smtpHostname = "smtp.gmail.com";
			int     smtpPort     = 587;
			boolean useSsl       = true;
			int     sslPort      = 465;
			boolean startTls     = true;
			String  username     = "dbxtune.alarms@gmail.com";
			String  password     = "xxxxxxxxxxxxxxxxxxx";
			List<String> toList  = List.of("goran.schwarz@executeit.se");
			String from          = username;

			String msgSubject = "XXXXXXXXXXXX";
			
			email.setHostName(smtpHostname);

			// CharSet
			email.setCharset(EmailConstants.UTF_8);
			
			// SMTP PORT
			if (smtpPort >= 0)
				email.setSmtpPort(smtpPort);

			// USE SSL
			if (useSsl)
				email.setSSLOnConnect(useSsl);

			// SSL PORT
			if (sslPort >= 0)
				email.setSslSmtpPort(sslPort+""); // Hmm why is this a String parameter?

			// START TLS
			if (startTls)
				email.setStartTLSEnabled(startTls);
			
			// AUTHENTICATION
			if (StringUtil.hasValue(username))
				email.setAuthentication(username, password);
			
			// add TO
//			for (String to : _toList)
			for (String to : toList)
				email.addTo(to);

			// add CC
//			for (String cc : _ccList)
//				email.addCc(cc);

			// FROM
//			email.setFrom(_from);
			String fromMailAddress = StringUtil.parseMailFromAddress_getEmailAddress(from);
			String fromDisplayName = StringUtil.parseMailFromAddress_getDisplayName (from);
			email.setFrom(fromMailAddress, fromDisplayName);

		
		
			// SUBJECT
			email.setSubject(msgSubject);

//			// CONTENT HTML or PLAIN
//			if (reportContent.isShortMessageOfHtml())
//			{
//				email.setHtmlMsg(msgBody);
//
//				// Client do not have HTML support
//				email.setTextMsg("Your email client does not support HTML messages, see DbxCentral to read the report!");
//			}
//			else
//			{
//				email.setTextMsg(msgBody);
//			}
			email.setHtmlMsg(msgBody);
		
			// SEND
			email.send();
		}
		catch (Exception ex) 
		{
			ex.printStackTrace();
		}
	}

	private static void openInBrowser(File f)
	{
		File reportFile = f;//report.getReportFile();
		if (reportFile == null)
			return;

		if (Desktop.isDesktopSupported())
		{
			Desktop desktop = Desktop.getDesktop();
			if ( desktop.isSupported(Desktop.Action.BROWSE) )
			{
				try
				{
//					desktop.browse(rr.getUrl().toURI());
					desktop.browse(reportFile.toURI());
				}
				catch (Exception ex)
				{
					_logger.error("Problems when open the URL '"+reportFile+"'. Caught: "+ex, ex);
				}
			}
		}
	}
	
}
	