/*
 * Automatically generated by jrpcgen 1.0.7 on 2009-03-10 14:34
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package asemon.rstat;
/**
 * A collection of constants used by the "rstat" ONC/RPC program.
 */
public interface rstat {
    public static final int RSTATVERS_SWTCH = 2;
    public static final int RSTATPROC_HAVEDISK_3 = 2;
    public static final int RSTATPROC_HAVEDISK_2 = 2;
    public static final int RSTATPROC_HAVEDISK_1 = 2;
    public static final int RSTATVERS_USERS = 5;
    public static final int RSTATPROG = 100001;
    public static final int DK_NDRIVE = 4;
    public static final int RSTATVERS_ORIG = 1;
    public static final int RSTATPROC_STATS_5 = 1;
    public static final int CPUSTATES = 4;
    public static final int RSTATPROC_STATS_4 = 1;
    public static final int RSTATPROC_STATS_3 = 1;
    public static final int RSTATPROC_STATS_2 = 1;
    public static final int RSTATPROC_STATS_1 = 1;
    public static final int RSTATVERS_TIME = 3;
    public static final int RSTATPROC_HAVEDISK_5 = 2;
    public static final int RSTATPROC_HAVEDISK_4 = 2;
    public static final int RSTATVERS_VAR = 4;
}
// End of rstat.java
